[package]
name = "quiet-stroll"
version = "0.3.3"
edition = "2021"
authors = ["Philippe Llerena"]
description = "A web sever to deliver basic File System informations"
readme = "README.md"
license-file = "LICENSE"
documentation = "https://github.com/doubleailes/quiet-stroll/blob/main/README.md"
repository = "https://github.com/doubleailes/quiet-stroll"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.5"
serde_json = "1.0.91"
glob = "0.3.1"
schemars = "0.7"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.rocket_okapi]
version = "0.8.0-rc.2"
features = ["swagger"]
